name: Update Homebrew Tap

on:
  release:
    types: [published]

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
    
    - name: Download release assets
      uses: robinraju/release-downloader@v1.8
      with:
        latest: true
        fileName: "*.tar.gz"
    
    - name: Calculate SHA256
      id: sha256
      run: |
        echo "osx_arm64_sha=$(sha256sum ServiceBusExplorer-osx-arm64.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT
        echo "osx_x64_sha=$(sha256sum ServiceBusExplorer-osx-x64.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT
        echo "linux_x64_sha=$(sha256sum ServiceBusExplorer-linux-x64.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT
    
    - name: Checkout tap repo
      uses: actions/checkout@v4
      with:
        repository: haga0531/homebrew-service-bus-explorer
        token: ${{ secrets.TAP_REPO_TOKEN }}
        path: tap
    
    - name: Update Formula
      run: |
        VERSION="${{ github.event.release.tag_name }}"
        VERSION_NUM="${VERSION#v}"
        
        cd tap
        
        # Update version
        sed -i "s/version \".*\"/version \"$VERSION_NUM\"/" Formula/service-bus-explorer.rb
        
        # Update SHA256
        sed -i "0,/sha256 \".*\"/s//sha256 \"${{ steps.sha256.outputs.osx_arm64_sha }}\"/" Formula/service-bus-explorer.rb
        sed -i "0,/sha256 \".*\"/s//sha256 \"${{ steps.sha256.outputs.osx_x64_sha }}\"/" Formula/service-bus-explorer.rb
        sed -i "0,/sha256 \".*\"/s//sha256 \"${{ steps.sha256.outputs.linux_x64_sha }}\"/" Formula/service-bus-explorer.rb
        
        # Update URLs if repository changed
        sed -i "s|https://github.com/.*/service-bus-explorer-crossplat/|https://github.com/${{ github.repository }}/|g" Formula/service-bus-explorer.rb
    
    - name: Commit and push
      run: |
        cd tap
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add Formula/service-bus-explorer.rb
        git commit -m "Update Service Bus Explorer to ${{ github.event.release.tag_name }}"
        git push
